[profile.default]
libs = ["lib"]
names = true
solc_version = "0.8.28"
sizes = true
via_ir = true
optimizer = true
optimizer_runs = 999999
bytecode_hash = "none"
evm_version = "paris"
out = "out"
src = "contracts"


[profile.default.invariant]
runs = 16
depth = 256
fail_on_revert = true

[profile.default.fmt]
wrap_comments = true


[profile.build]
test = "/dev/null"
script = "/dev/null"

[profile.test]
via-ir = false
